### ISSUE TITLE
No remove button for managed brooks and users

### ISSUE THREAD

**Issue by Slhdono** [txthinking/brook-manager#16]
There is no remove button for managed brooks and users, I can only ban users which will not stop their links from working and if I wanna edit a managed brook all options are disabled, I can't remove or disable the links deployed on it, also it would be nice to be able to deploy links again in case the destination machine got restarted.

Thank you for your amazing work btw, these are just suggestions in case you wanted to upgrade the work.

**Comment by txthinking** [comment]
You got it wrong. it will stop automatically
