### ISSUE TITLE
执行完您写在readme里的命令后无法访问

### ISSUE THREAD

**Issue by hanshoukai** [txthinking/brook-manager#2]
![1663655264829](https://user-images.githubusercontent.com/8869367/191183468-c3d8f763-4414-49ff-a2c9-5f63ab05df12.jpg)
如上图我执行完之后无法进行访问，求大佬指教

**Comment by txthinking** [comment]
joker log `joker last`

**Comment by 3H54N** [comment]
> 

2022/10/20 19:42:44 http: proxy error: dial tcp 127.0.0.1:8080: connect: connection refused
2022/10/20 19:42:44 http: proxy error: dial tcp 127.0.0.1:8080: connect: connection refused
2022/10/20 19:42:50 http: proxy error: dial tcp 127.0.0.1:8080: connect: connection refused
2022/10/20 19:42:54 http: proxy error: dial tcp 127.0.0.1:8080: connect: connection refused
2022/10/20 19:43:59 http: proxy error: dial tcp 127.0.0.1:8080: connect: connection refused
2022/10/20 19:44:07 http: proxy error: dial tcp 127.0.0.1:8080: connect: connection refused
2022/10/20 19:45:29 http: proxy error: dial tcp 127.0.0.1:8080: connect: connection refused
2022/10/20 19:46:07 http: proxy error: dial tcp 127.0.0.1:8080: connect: connection refused
2022/10/20 19:49:34 http: proxy error: dial tcp 127.0.0.1:8080: connect: connection refused
2022/10/20 19:49:35 http: proxy error: dial tcp 127.0.0.1:8080: connect: connection refused
2022/10/20 19:49:35 http: proxy error: dial tcp 127.0.0.1:8080: connect: connection refused
2022/10/20 19:49:41 http: proxy error: dial tcp 127.0.0.1:8080: connect: connection refused
2022/10/20 19:49:50 http: proxy error: dial tcp 127.0.0.1:8080: connect: connection refused

**Comment by txthinking** [comment]
EN: https://www.youtube.com/watch?v=_0LnLO5Xat8
ZH: https://www.youtube.com/watch?v=KNAHFA711o8
