### ISSUE TITLE
How to use this manager without anythings only nginx reverse proxy?

### ISSUE THREAD

**Issue by Handsome1080P** [txthinking/brook-manager#3]
How to use this manager without anythings only nginx proxy?I dislike install all useless things in my system,I only install nginx.And seems it can't reverse this program.I already set domain in nginx and still notice me no domain.

**Comment by txthinking** [comment]
just type the domain(which is you already set in nginx) in the admin page
and save.
because the backend does not know your domain exactly

**Comment by Handsome1080P** [comment]
> 

Thx for reply.Admin page can direct access?IDK,I will try again.
