### ISSUE TITLE
How to custom my own UI?

### ISSUE THREAD

**Issue by Handsome1080P** [txthinking/brook-manager#4]
How to custom my own UI?Need modify the source and rebuild and select my own ui in the CLI?
Suggestion: Load my own setting/UI from a config folder can be more convenience.

**Comment by txthinking** [comment]
https://github.com/txthinking/brook-manager#developer-%E5%BC%80%E5%8F%91%E8%80%85

https://github.com/txthinking/brook-manager#file-introduction-%E6%96%87%E4%BB%B6%E4%BB%8B%E7%BB%8D

https://github.com/txthinking/brook-manager/blob/master/LICENSE
